$content = @'
es_siniestro_vial,fecha_siniestro,hora_aprox,tipo_siniestro,tipo_ubicacion,ubicacion_calle1,ubicacion_calle2,altura,ruta_nombre,kilometro,ciudad,vehiculos_involucrados,hubo_peatones,cantidad_heridos,cantidad_fallecidos,gravedad,resumen_breve,url,clima_real,lluvia_mm
True,2026-08-03,01:55,vuelco,altura,San Juan,,3900,,,Rosario,Citroën C3,False,0,0,Leve,Un hombre de 31 años volcó su vehículo Citroën C3 en San Juan al 3900 durante la madrugada.,https://www.rosario3.com/informaciongeneral/volco-un-auto-tras-chocar-con-un-camion-y-hay-demoras-en-la-autopista-rosario-buenos-aires-20260803-0014.html,Nublado,0.0
True,2026-07-27,12:00,colision_multiple,interseccion,Paraguay,Gálvez,,,,Rosario,"Chevrolet, Peugeot, Automóvil estacionado",False,2,0,Moderado,"Triple choque entre dos vehículos en circulación y uno estacionado en Rosario, dejando dos mujeres con heridas leves.",https://www.rosario3.com/informaciongeneral/triple-choque-en-rosario-y-desvios-de-transito-hay-doble-cartel-de-pare-pero-no-frena-nadie-20260727-0054.html,Nublado,0.0
True,2026-08-10,06:00,choque,altura,San Juan,,1900,,,Rosario,Automóvil,False,0,0,Leve,"Un conductor se distrajo al ponerse el cinturón, perdió el control y chocó contra un árbol y una valla escolar.",https://www.rosario3.com/informaciongeneral/se-distrajo-y-choco-contra-un-arbol-y-el-vallado-de-una-escuela-del-centro-de-rosario-20260810-0011.html,Nublado,0.0
True,2026-08-10,21:30,choque,interseccion,Mendoza,Servando Bayo,,,,Rosario,Chevrolet Aveo,False,0,0,Leve,Automovilista se descompensó y chocó contra un local en Echesortu; no se reportaron heridos de consideración.,https://www.rosario3.com/policiales/un-automovilista-se-descompenso-perdio-el-control-y-choco-contra-el-frente-de-un-local-de-echesortu-20260811-0011.html,Nublado,0.0
True,2026-08-06,Desconocido,atropello,interseccion,Barra,27 de Febrero,,,,Rosario,"automovil, motocicleta",False,1,0,Grave,"Un automovilista chocó a un motociclista en Barra y 27 de Febrero, dejándolo herido y dándose a la fuga.",https://www.rosario3.com/informaciongeneral/video-asi-fue-el-choque-del-automovilista-que-embistio-una-moto-y-huyo-20260806-0041.html,Lluvia intensa,43.3
True,2026-08-18,Desconocido,choque,interseccion,Ayacucho,Riobamba,,,,Rosario,"Volkswagen Fox, Fiat Palio",False,0,0,Leve,Violento choque entre un Volkswagen Fox y un Fiat Palio en la intersección de Ayacucho y Riobamba.,https://www.rosario3.com/informaciongeneral/violento-choque-entre-dos-autos-en-ayacucho-y-riobamba-20260818-0084.html,Llovizna,2.6
True,2026-07-31,01:55,vuelco,altura,San Juan,,3940,,,Rosario,Citroën C3,False,0,0,Leve,Un joven volcó su Citroën C3 en calle San Juan al 3940 tras morder el cordón. No hubo heridos.,https://www.rosario3.com/informaciongeneral/mordio-el-cordon-con-su-auto-y-volco-en-echesortu-20260731-0008.html,Lluvia,9.4
True,2026-08-14,22:30,colision_multiple,interseccion,Avenida Rivarola,Fader,,,,Rosario,"Colectivo linea 121, Peugeot Partner Patagonica, Peugeot 308, Peugeot 408",False,0,0,Leve,"Un colectivo de la linea 121 colisiono contra tres autos estacionados en barrio Godoy, sin dejar personas heridas.",https://www.rosario3.com/informaciongeneral/choque-en-barrio-godoy-un-colectivo-colisiono-contra-tres-autos-estacionados-20260815-0004.html,Llovizna,2.6
True,2026-08-14,21:05,choque,interseccion,Avenida Circunvalacion,Avenida Pellegrini,,,,Rosario,"Motocicleta Motomel S2 150 cc, Camion con acoplado",False,2,0,Grave,Dos hombres en motocicleta resultaron heridos tras colisionar con un camión en Avenida Circunvalación y Pellegrini.,https://www.rosario3.com/policiales/fuerte-choque-en-circunvalacion-dos-hombres-heridos-tras-caer-con-su-moto-debajo-de-un-acoplado-20260815-0003.html,Llovizna,2.6
True,2026-07-27,05:45,choque,interseccion,Ruta 34,Circunvalacion,,,,Rosario,"Peugeot, moto Bajaj Rouser 200",False,0,0,Leve,Colisión entre un auto Peugeot y una moto en Ruta 34 y Circunvalación sin personas heridas.,https://www.rosario3.com/informaciongeneral/fuerte-choque-entre-un-auto-y-un-moto-en-la-ruta-34-y-circunvalacion-de-rosario-20260727-0012.html,Nublado,0.0
True,2026-08-10,Desconocido,colision_multiple,altura,Avenida Presidente Perón,,4000,,,Rosario,"Chevrolet Aveo, Ford EcoSport, Volkswagen Suran",False,1,0,Leve,Triple choque en avenida Presidente Perón al 4000 dejó una mujer herida y generó desvíos en el tránsito.,https://www.rosario3.com/informaciongeneral/fuerte-triple-choque-en-zona-oeste-dejo-heridos-y-genero-cortes-en-avenida-peron-20260811-0031.html,Nublado,0.0
True,2026-08-20,06:30,choque,interseccion,Ovidio Lagos,Rioja,,,,Rosario,"auto, moto",False,1,0,Moderado,Choque entre auto y moto en Ovidio Lagos y Rioja durante hora pico; un herido trasladado al Sanatorio Mapaci.,https://www.rosario3.com/informaciongeneral/caos-de-transito-en-hora-pico-en-ovidio-lagos-y-rioja-por-un-choque-entre-un-auto-y-una-moto-20260820-0007.html,Nublado,0.0
True,2026-07-08,08:30,choque,interseccion,Avenida Rivarola,Danieri,,,,Rosario,"Motomel DLX 110, Renault 19, Automóvil",False,0,1,Fatal,"Un motociclista de 26 años falleció tras chocar contra vehículos en avenida Rivarola y Danieri, Rosario.",https://www.lacapital.com.ar/la-ciudad/fallecieron-dos-motociclistas-la-zona-oeste-poco-mas-12-horas-diferencia-n10268604.html,Nublado,0.0
True,2026-07-17,23:30,vuelco,interseccion,España,Brown,,,,Rosario,"Jeep Compact, Peugeot 208, Renault Clio",False,0,0,Leve,"Un Jeep volcó tras chocar con un Peugeot 208, afectando también a vehículos estacionados en Rosario. Sin heridos.",https://www.lacapital.com.ar/la-ciudad/un-choque-impresionante-termino-un-jeep-dado-vuelta-el-centro-rosario-n10270192.html,Lluvia,10.5
True,2026-07-07,07:00,choque,interseccion,avenida Eva Perón,Colombia,,,,Rosario,vehículo de gran porte,False,0,0,Leve,Un vehículo de gran porte enganchó cables y derribó un semáforo en avenida Eva Perón y Colombia.,https://www.lacapital.com.ar/la-ciudad/insolito-corte-transito-rosario-un-semaforo-se-partio-y-cayo-plena-calle-n10268399.html,Nublado,0.0
True,2026-06-16,22:30,choque,interseccion,Bulevar Oroño,Gaboto,,,,Rosario,"Motocicleta Yamaha Tenere 250cc, Colectivo Linea 129",False,0,1,Fatal,Un motociclista falleció tras colisionar con un colectivo de la línea 129 en Bulevar Oroño y Gaboto.,https://www.lacapital.com.ar/la-ciudad/fallecio-un-motociclista-luego-un-choque-un-colectivo-bulevar-orono-n10264915.html,Nublado,0.0
True,2026-08-20,08:00,colision_multiple,interseccion,Avenida Circunvalación,Avenida Pellegrini,,,,Rosario,"3 autos, Renault Kangoo",False,0,0,Leve,"Choque múltiple de cuatro vehículos en Avenida Circunvalación y Pellegrini en Rosario, generando demoras sin heridos graves reportados.",https://www.lacapital.com.ar/la-ciudad/un-choque-multiple-avenida-circunvalacion-provoco-importantes-demoras-este-jueves-n10276307.html,Nublado,0.0
True,2026-05-13,05:00,choque,altura,Avenida San Martín,,2900,,,Rosario,Fiat Palio,False,0,1,Fatal,Automovilista de 36 años murió tras despistarse y chocar contra dos viviendas en Rosario durante la madrugada.,https://www.lacapital.com.ar/la-ciudad/choque-estremecedor-y-vecinos-atrapados-un-automovilista-murio-la-colision-n10259091.html,Nublado,0.0
True,2026-05-13,05:20,choque,interseccion,Avenida San Martín,Amenábar,,,,Rosario,Fiat Palio,False,1,1,Fatal,Un conductor de 36 años falleció tras chocar su vehículo contra dos viviendas en la ciudad de Rosario.,https://www.lacapital.com.ar/la-ciudad/un-video-muestra-la-mecanica-del-choque-fatal-la-zona-sur-n10259130.html,Nublado,0.0
True,2026-05-13,16:00,vuelco,interseccion,Santa Fe,bulevar Avellaneda,,,,Rosario,"Toyota Yaris, Citroën C4",False,0,0,Leve,Siniestro vial en Rosario entre dos vehículos que terminó con el vuelco de uno de ellos. Sin heridos graves.,https://www.lacapital.com.ar/la-ciudad/una-diputada-provincial-protagonizo-un-siniestro-vial-la-zona-oeste-rosario-no-hubo-heridos-gravedad-n10259230.html,Nublado,0.0
True,2026-05-01,07:30,atropello,altura,avenida Dante Alighieri,,,,,Rosario,"KIA Soul, bicicleta Fuji Adventure 27.5 Comp",True,1,0,Leve,"Conductora alcoholizada atropelló a un ciclista en avenida Dante Alighieri e intentó huir, siendo detenida posteriormente por la policía.",https://www.lacapital.com.ar/la-ciudad/choco-un-ciclista-bulevar-orono-mientras-manejaba-alcoholizada-e-intento-huir-n10257281.html,Nublado,0.0
True,2026-05-01,08:00,vuelco,interseccion,Avenida Pellegrini,Pascual Rosas,,,,Rosario,"Peugeot 307, Chevrolet Corsa",False,0,0,Leve,Un Peugeot 307 volcó y chocó contra un Chevrolet Corsa en avenida Pellegrini y Pascual Rosas en Rosario.,https://www.lacapital.com.ar/la-ciudad/un-choque-impresionante-avenida-pellegrini-termino-un-auto-dado-vuelta-n10257107.html,Nublado,0.0
True,2026-02-17,23:30,atropello,interseccion,Avenida Circunvalación,Doctor Vicente Medina,,,,Rosario,"Honda Wave, Camión",False,0,1,Fatal,Un motociclista murió atropellado por un camión que se dio a la fuga en Circunvalación y Doctor Vicente Medina.,https://www.lacapital.com.ar/la-ciudad/choque-circunvalacion-murio-un-motociclista-y-denuncian-que-un-conductor-se-fugo-n10245296.html,Llovizna,0.5
True,2026-04-04,00:00,choque,interseccion,Avenida Pellegrini,España,,,,Rosario,"Motocicleta Corven Energy, Peugeot 206",False,1,0,Moderado,"Motociclista robado cruzó en rojo en Rosario, chocó contra un Peugeot 206 y resultó herido.",https://www.lacapital.com.ar/policiales/robo-huyo-y-termino-el-hospital-despues-un-choque-haber-cruzado-rojo-n10252575.html,Lluvia,8.5
True,2026-03-16,07:50,colision_multiple,interseccion,Avenida Circunvalación,Avenida Presidente Perón,,,,Rosario,"Dodge RAM, Toyota Hilux, Fiat Punto, Peugeot 208, Pick up adicional",False,0,0,Leve,"Choque en cadena de cinco vehículos en Circunvalación, Rosario, causado por intentar esquivar un perro suelto. Sin heridos.",https://www.lacapital.com.ar/la-ciudad/un-perro-suelto-avenida-circunvalacion-provoco-un-gran-choque-cadena-n10249440.html,Parcialmente nublado,0.0
True,2026-03-26,05:30,choque,interseccion,Avenida Pellegrini,Maipú,,,,Rosario,"Taxi Fiat Cronos, Volkswagen Gol",False,2,0,Leve,Un taxi y un auto particular colisionaron en Pellegrini y Maipú; hubo dos heridos leves y daños materiales.,https://www.lacapital.com.ar/la-ciudad/un-choque-fortisimo-avenida-pellegrini-termino-un-taxi-y-otro-auto-destrozados-n10251072.html,Nublado,0.0
True,2026-01-13,08:30,atropello,interseccion,Ocampo,Constitucion,,,,Rosario,Volkswagen,True,1,0,Moderado,Una menor de 15 años atropelló a un operario y chocó contra un contenedor y un inmueble en Rosario.,https://www.lacapital.com.ar/la-ciudad/choques-auto-y-un-hombre-atropellado-una-chica-15-anos-cual-es-la-sancion-n10239852.html,Lluvia,1.6
True,2026-01-14,12:00,choque,interseccion,Avenida Circunvalación,Uriburu,,,,Rosario,"Camión Ford Cargo 1722, Camión con volquete",False,1,0,Moderado,Choque de dos camiones en Circunvalación y Uriburu; un chofer resultó herido y debió ser rescatado por bomberos.,https://www.lacapital.com.ar/la-ciudad/choque-camiones-circunvalacion-y-uriburu-un-chofer-quedo-atrapado-n10239918.html,Llovizna,0.9
True,2026-01-13,06:30,atropello,interseccion,27 de Febrero,Circunvalación,,,,Rosario,Camión,True,0,1,Fatal,Camionero fallece tras ser presuntamente atropellado por otro camión en el ingreso al puerto de Rosario.,https://www.lacapital.com.ar/la-ciudad/tragedia-el-puerto-rosario-investigan-la-muerte-un-camionero-la-entrada-n10239637.html,Lluvia,1.6
True,2026-02-06,11:00,atropello,interseccion,Bulevar Rondeau,Vila,,,,Rosario,Peugeot Partner,True,0,1,Fatal,"Un hombre falleció tras ser atropellado por una camioneta en el cruce de Bulevar Rondeau y calle Vila, Rosario.",https://www.lacapital.com.ar/la-ciudad/muerte-zona-norte-un-hombre-fue-atropellado-cuando-cruzaba-bulevar-rondeau-n10243561.html,Llovizna,0.2
True,2026-05-18,06:45,atropello,interseccion,avenida Circunvalación,avenida Uriburu,,,,Rosario,"Motocicleta, Camión, Toyota Hilux",False,0,1,Fatal,Un motociclista murió al chocar contra un camión en Circunvalación y Uriburu; una Hilux atropelló luego la moto.,https://www.lacapital.com.ar/la-ciudad/un-motociclista-fallecio-un-choque-un-camion-avenida-circunvalacion-n10259844.html,Despejado,0.0
True,2026-08-19,10:30,choque,interseccion,Dean Funes,Moreno,,,,Rosario,"Motocicleta Honda Titan, Auto particular",False,0,1,Fatal,Un policía en moto murió tras derrapar e impactar contra un árbol en Rosario al esquivar un auto fugitivo.,https://www.lacapital.com.ar/policiales/un-policia-fuera-servicio-murio-un-siniestro-vial-la-zona-sur-rosario-n10276174.html,Nublado,0.0
True,2026-08-12,03:30,choque,interseccion,Donizetti,Artilleros,,,,Rosario,Volkswagen Suran,False,1,0,Leve,"Ladrones robaron un Volkswagen Suran de Didi y chocaron contra una columna en Rosario, dejando un detenido herido.",https://www.lacapital.com.ar/policiales/increible-robo-fallido-chocaron-un-auto-didi-y-un-ladron-termino-el-piso-n10274824.html,Llovizna,0.2

'@
[System.IO.File]::WriteAllText('siniestros_rosario.csv', $content, [System.Text.UTF8Encoding]::new($true))
